server:
  port: 80
# datasource
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.10.108:3306/db_crm?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456


#mybatis
mybatis:
  #mapper映射文件的位置，指向的是resources目录下的
  mapper-locations: classpath:/mapper/*.xml
  # 开启驼峰命名
  map-underscore-to-camel-case: true
  # 别名
  type-aliases-package: com.et.entity
# logging
logging:
  level:
    com:
      et: debug
